// https://cs.android.com/android/platform/superproject/+/android14-qpr3-release:tools/carrier_settings/proto/carrier_list.proto

//
// Copyright (C) 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.6
// source: carrier_list.proto

package carrierlist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The carrier ID is matched against SIM data to determine carrier
type CarrierId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Mobile Country Code (MCC) & Mobile Network Code (MNC)
	MccMnc *string `protobuf:"bytes,1,opt,name=mcc_mnc,json=mccMnc" json:"mcc_mnc,omitempty"`
	// Additional data to identify MVNO
	//
	// Types that are assignable to MvnoData:
	//
	//	*CarrierId_Spn
	//	*CarrierId_Imsi
	//	*CarrierId_Gid1
	MvnoData isCarrierId_MvnoData `protobuf_oneof:"mvno_data"`
}

func (x *CarrierId) Reset() {
	*x = CarrierId{}
	mi := &file_carrier_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarrierId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarrierId) ProtoMessage() {}

func (x *CarrierId) ProtoReflect() protoreflect.Message {
	mi := &file_carrier_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarrierId.ProtoReflect.Descriptor instead.
func (*CarrierId) Descriptor() ([]byte, []int) {
	return file_carrier_list_proto_rawDescGZIP(), []int{0}
}

func (x *CarrierId) GetMccMnc() string {
	if x != nil && x.MccMnc != nil {
		return *x.MccMnc
	}
	return ""
}

func (m *CarrierId) GetMvnoData() isCarrierId_MvnoData {
	if m != nil {
		return m.MvnoData
	}
	return nil
}

func (x *CarrierId) GetSpn() string {
	if x, ok := x.GetMvnoData().(*CarrierId_Spn); ok {
		return x.Spn
	}
	return ""
}

func (x *CarrierId) GetImsi() string {
	if x, ok := x.GetMvnoData().(*CarrierId_Imsi); ok {
		return x.Imsi
	}
	return ""
}

func (x *CarrierId) GetGid1() string {
	if x, ok := x.GetMvnoData().(*CarrierId_Gid1); ok {
		return x.Gid1
	}
	return ""
}

type isCarrierId_MvnoData interface {
	isCarrierId_MvnoData()
}

type CarrierId_Spn struct {
	// SPN (Service Provider Name)
	Spn string `protobuf:"bytes,2,opt,name=spn,oneof"`
}

type CarrierId_Imsi struct {
	// IMSI prefix pattern
	Imsi string `protobuf:"bytes,3,opt,name=imsi,oneof"`
}

type CarrierId_Gid1 struct {
	// Group identifier (level 1) prefix
	Gid1 string `protobuf:"bytes,4,opt,name=gid1,oneof"`
}

func (*CarrierId_Spn) isCarrierId_MvnoData() {}

func (*CarrierId_Imsi) isCarrierId_MvnoData() {}

func (*CarrierId_Gid1) isCarrierId_MvnoData() {}

// Maps CarrierIds to an internal unique carrier name
type CarrierMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique canonical carrier name
	// This name is the primary key to identify a carrier
	// Typically a canonical_name looks like <carrier_name>_<iso_country_code>
	CanonicalName *string `protobuf:"bytes,1,opt,name=canonical_name,json=canonicalName" json:"canonical_name,omitempty"`
	// A collection of network IDs owned by this carrier
	CarrierId []*CarrierId `protobuf:"bytes,2,rep,name=carrier_id,json=carrierId" json:"carrier_id,omitempty"`
}

func (x *CarrierMap) Reset() {
	*x = CarrierMap{}
	mi := &file_carrier_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarrierMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarrierMap) ProtoMessage() {}

func (x *CarrierMap) ProtoReflect() protoreflect.Message {
	mi := &file_carrier_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarrierMap.ProtoReflect.Descriptor instead.
func (*CarrierMap) Descriptor() ([]byte, []int) {
	return file_carrier_list_proto_rawDescGZIP(), []int{1}
}

func (x *CarrierMap) GetCanonicalName() string {
	if x != nil && x.CanonicalName != nil {
		return *x.CanonicalName
	}
	return ""
}

func (x *CarrierMap) GetCarrierId() []*CarrierId {
	if x != nil {
		return x.CarrierId
	}
	return nil
}

// Maps CarrierId to internal unique carrier name
type CarrierList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A collection of carrier maps; one entry for one carrier
	Entry []*CarrierMap `protobuf:"bytes,1,rep,name=entry" json:"entry,omitempty"`
	// The version number of this CarrierList file
	Version *int64 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (x *CarrierList) Reset() {
	*x = CarrierList{}
	mi := &file_carrier_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarrierList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarrierList) ProtoMessage() {}

func (x *CarrierList) ProtoReflect() protoreflect.Message {
	mi := &file_carrier_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarrierList.ProtoReflect.Descriptor instead.
func (*CarrierList) Descriptor() ([]byte, []int) {
	return file_carrier_list_proto_rawDescGZIP(), []int{2}
}

func (x *CarrierList) GetEntry() []*CarrierMap {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *CarrierList) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

var File_carrier_list_proto protoreflect.FileDescriptor

var file_carrier_list_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x22, 0x77, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x72,
	0x69, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x63, 0x63, 0x5f, 0x6d, 0x6e, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x63, 0x63, 0x4d, 0x6e, 0x63, 0x12, 0x12,
	0x0a, 0x03, 0x73, 0x70, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73,
	0x70, 0x6e, 0x12, 0x14, 0x0a, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x12, 0x14, 0x0a, 0x04, 0x67, 0x69, 0x64, 0x31,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x67, 0x69, 0x64, 0x31, 0x42, 0x0b,
	0x0a, 0x09, 0x6d, 0x76, 0x6e, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x4a, 0x04, 0x08, 0x05, 0x10,
	0x06, 0x22, 0x77, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63,
	0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x2e,
	0x43, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x49, 0x64, 0x52, 0x09, 0x63, 0x61, 0x72, 0x72, 0x69,
	0x65, 0x72, 0x49, 0x64, 0x4a, 0x04, 0x08, 0x03, 0x10, 0x04, 0x22, 0x5d, 0x0a, 0x0b, 0x43, 0x61,
	0x72, 0x72, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x43, 0x61,
	0x72, 0x72, 0x69, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x15, 0x42, 0x11, 0x43, 0x61, 0x72,
	0x72, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x50, 0x01,
}

var (
	file_carrier_list_proto_rawDescOnce sync.Once
	file_carrier_list_proto_rawDescData = file_carrier_list_proto_rawDesc
)

func file_carrier_list_proto_rawDescGZIP() []byte {
	file_carrier_list_proto_rawDescOnce.Do(func() {
		file_carrier_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_carrier_list_proto_rawDescData)
	})
	return file_carrier_list_proto_rawDescData
}

var file_carrier_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_carrier_list_proto_goTypes = []any{
	(*CarrierId)(nil),   // 0: com.google.carrier.CarrierId
	(*CarrierMap)(nil),  // 1: com.google.carrier.CarrierMap
	(*CarrierList)(nil), // 2: com.google.carrier.CarrierList
}
var file_carrier_list_proto_depIdxs = []int32{
	0, // 0: com.google.carrier.CarrierMap.carrier_id:type_name -> com.google.carrier.CarrierId
	1, // 1: com.google.carrier.CarrierList.entry:type_name -> com.google.carrier.CarrierMap
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_carrier_list_proto_init() }
func file_carrier_list_proto_init() {
	if File_carrier_list_proto != nil {
		return
	}
	file_carrier_list_proto_msgTypes[0].OneofWrappers = []any{
		(*CarrierId_Spn)(nil),
		(*CarrierId_Imsi)(nil),
		(*CarrierId_Gid1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_carrier_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carrier_list_proto_goTypes,
		DependencyIndexes: file_carrier_list_proto_depIdxs,
		MessageInfos:      file_carrier_list_proto_msgTypes,
	}.Build()
	File_carrier_list_proto = out.File
	file_carrier_list_proto_rawDesc = nil
	file_carrier_list_proto_goTypes = nil
	file_carrier_list_proto_depIdxs = nil
}
